name: Deploy React App to Azure Static Web Apps

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build React App
        run: |
          # If your React app is in a specific folder
          cd frontend  # or whatever your folder name is
          npm install
          npm run build

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_aps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "frontend"  # Path to your app
          output_location: "build"
          skip_app_build: true
